language: c
env:
  global:
    - ocaml_ppa=avsm/ppa
  matrix:
    - subdir=python task=test-py2
    - subdir=python task=test-py3
    - subdir=ocaml task=test
    - task=permutation-test
notifications:
  email: false

before_install:
 - |
      set -eux
      export subdir=${subdir:-.}
      if [ $subdir != python ]; then
        # ./ocaml or ./
        echo "yes" | sudo add-apt-repository "ppa:$ocaml_ppa"
        sudo apt-get update -qq
        export OPAMYES=yes # no questions
        sudo apt-get install -qq ocaml opam

        opam init --no-setup
        eval "$(opam config env)"
        opam update

        opam_deps="$(grep -E -o '"[^"]+"' nix/opam-dep-names.nix | grep -v '[<=>]' | sed -e 's/[]["]//g')"
        opam install $opam_deps ounit
      else
        sudo apt-get update -qq
      fi

      if [ $subdir != ocaml ]; then
        # ./python or ./
        sudo apt-get install -qq pychecker mono-gmcs
      fi
      if [ "$task" = "test-py3" ]; then
        sudo apt-get install -qq python3 python3-gi
      fi

      sudo apt-get install zeroinstall-injector
      # not required, just useful for colour-coding of test results
      0install run \
        http://gfxmonk.net/dist/0install/zeroinstall-plugin-manager.xml \
        http://gfxmonk.net/dist/0install/nosetests-runner.xml \
        --plugin-add http://gfxmonk.net/dist/0install/rednose.xml
      set +eux

script: "cd $subdir && make $task"

