language: nix
sudo: false
env:
  matrix:
    - target=ci-python2
    - target=ci-python3
    - target=ci-ocaml
    - target=ci-opam
    - target=ci-permutation
notifications:
  email: false
script:
  - git archive HEAD --format=tar.gz --prefix=git-export/ > nix/local.tgz
  - make "$target"
